import type { PracticeScenario } from './state-machine'

export const scenarios: PracticeScenario[] = [
  {
    id: 'fire-grounded-flow',
    note: '문을 닫고, 계단을 찾고, 막히면 도움을 불러요',
    posterSrc: '/demo/fire-grounded-02.jpg',
    title: '화재가 났을 때',
    videoSrc: '/demo-video/fire-full-practice-001.mp4',
    segments: [
      {
        actionSteps: [],
        endMs: 11_500,
        id: 'fire-full-alert',
        label: '화재 연습을 시작해요',
        learnerExplanation: '아파트 화재 연습을 시작해요.',
        learnerPrompt: '숫자와 제목을 보고 있어요.',
        options: [],
        practiceMode: 'intro',
        question: '',
        startMs: 0,
      },
      {
        actionSteps: ['현관문을 닫아요', '계단으로 나가요'],
        endMs: 22_500,
        id: 'fire-full-door-control',
        label: '문 닫고 계단으로 가요',
        learnerExplanation: '현관문을 닫고 계단으로 나가요.',
        learnerPrompt: '우리 집에서 불이 났어요.',
        options: [
          { correct: true, id: 'close-door', label: '닫기' },
          { correct: false, id: 'open-door', label: '열어 두기' },
        ],
        question: '나갈 때 문은 어떻게 할까요?',
        startMs: 11_500,
      },
      {
        actionSteps: ['계단을 찾아요', '천천히 내려가요'],
        endMs: 27_500,
        id: 'fire-full-stairs',
        label: '계단으로 나가요',
        learnerExplanation: '불이 났을 때 엘리베이터는 타지 않아요.',
        learnerPrompt: '계단과 엘리베이터가 보여요.',
        options: [
          { correct: true, id: 'stairs', label: '계단' },
          { correct: false, id: 'elevator', label: '엘리베이터' },
        ],
        question: '어디로 대피할까요?',
        startMs: 22_500,
      },
      {
        actionSteps: [
          '대피공간으로 가요',
          '문을 닫아요',
          '대피공간 위치를 119나 어른에게 알려요',
        ],
        endMs: 35_500,
        id: 'fire-full-refuge',
        label: '대피공간으로 가요',
        learnerExplanation: '길이 막히면 대피공간에서 도움을 불러요.',
        learnerPrompt: '연기가 많아서 밖으로 나가기 어려워요.',
        options: [
          { correct: true, id: 'refuge', label: '대피공간(안전한 방)' },
          { correct: false, id: 'force-exit', label: '연기가 많은 길' },
        ],
        question: '밖으로 나가기 어려우면 어디로 갈까요?',
        startMs: 27_500,
      },
      {
        actionSteps: [
          '방문을 닫아요',
          '젖은 수건으로 문틈을 막아요',
          '방 안 위치를 119에 알려요',
        ],
        endMs: 43_500,
        id: 'fire-full-seal-room',
        label: '문틈을 막고 알려요',
        learnerExplanation: '방문을 닫고 문틈을 막아 119에 알려요.',
        learnerPrompt: '연기가 들어와서 바로 나가기 어려워요.',
        options: [
          { correct: true, id: 'seal-gap', label: '문틈 막기' },
          { correct: false, id: 'window-only', label: '창문만 열기' },
        ],
        question: '방 안에서 기다릴 때 무엇을 할까요?',
        startMs: 35_500,
      },
      {
        actionSteps: ['창문을 닫아요', '집 안에서 기다려요', '안내 방송을 들어요'],
        endMs: 53_000,
        id: 'fire-full-after-evacuation',
        label: '집 안에서 안내를 들어요',
        learnerExplanation: '연기가 안 들어오면 집 안에서 안내를 들어요.',
        learnerPrompt: '다른 집에 불이 났지만 우리 집은 괜찮아 보여요.',
        options: [
          { correct: true, id: 'listen-inside', label: '안내 방송 듣기' },
          { correct: false, id: 'go-hallway', label: '복도로 나가기' },
        ],
        question: '연기가 들어오지 않으면 무엇을 할까요?',
        startMs: 43_500,
      },
      {
        actionSteps: [],
        endMs: 60_000,
        id: 'fire-full-summary',
        label: '마지막 정리',
        learnerExplanation: '무조건 나가기보다 상황에 맞게 행동해요.',
        learnerPrompt: '마지막으로 전체 행동을 다시 말해요.',
        options: [],
        practiceMode: 'intro',
        question: '',
        startMs: 53_000,
      },
    ],
  },
  {
    id: 'earthquake-protect-flow',
    note: '머리를 지키고, 멈춘 뒤에는 어른과 주변을 봐요',
    posterSrc: '/demo/earthquake-review-02.jpg',
    title: '지진이 났을 때',
    videoSrc: '/demo-video/earthquake-full-practice-001.mp4',
    segments: [
      {
        actionSteps: [],
        endMs: 35_760,
        id: 'earthquake-full-opening',
        label: '지진 연습을 시작해요',
        learnerExplanation: '지진 때 어떻게 할지 배워요.',
        learnerPrompt: '지진은 갑자기 올 수 있어요.',
        options: [],
        practiceMode: 'intro',
        question: '',
        startMs: 0,
      },
      {
        actionSteps: ['몸을 낮춰요', '탁자 아래로 가요', '탁자 다리를 잡아요'],
        endMs: 54_880,
        id: 'earthquake-full-table-protect',
        label: '탁자 아래로 들어가요',
        learnerExplanation: '탁자 아래에서 다리를 꼭 잡아요.',
        learnerPrompt: '흔들림은 1~2분쯤 이어져요.',
        options: [
          { correct: true, id: 'under-table', label: '탁자 아래' },
          { correct: false, id: 'run-out', label: '밖으로 뛰기' },
        ],
        question: '흔들릴 때 어디로 갈까요?',
        startMs: 35_760,
      },
      {
        actionSteps: ['방석을 들어요', '머리를 가려요', '유리에 등을 돌려요'],
        endMs: 66_200,
        id: 'earthquake-full-cushion-glass',
        label: '방석으로 머리를 가려요',
        learnerExplanation: '방석으로 머리를 가리고 유리에 등을 돌려요.',
        learnerPrompt: '탁자가 없을 수 있어요.',
        options: [
          { correct: true, id: 'cushion', label: '방석' },
          { correct: false, id: 'face-glass', label: '유리 쪽' },
        ],
        question: '탁자가 없으면 무엇으로 머리를 가릴까요?',
        startMs: 54_880,
      },
      {
        actionSteps: [
          '가스 냄새를 어른에게 말해요',
          '가스 중간 밸브가 보이면 어른에게 말해요',
          '전기 고장이 보이면 어른에게 말해요',
        ],
        endMs: 74_920,
        id: 'earthquake-full-gas-electric',
        label: '가스와 전기는 어른에게 말해요',
        learnerExplanation: '가스 중간 밸브와 전기 고장은 어른에게 말해요.',
        learnerPrompt: '흔들림이 멈추면 가스와 전기를 봐요.',
        options: [
          { correct: true, id: 'tell-adult', label: '어른' },
          { correct: false, id: 'touch-alone', label: '혼자 만지기' },
        ],
        question: '가스 냄새가 나면 누구에게 말할까요?',
        startMs: 66_200,
      },
      {
        actionSteps: ['계단을 찾아요', '건물 밖으로 천천히 내려가요'],
        endMs: 81_520,
        id: 'earthquake-full-stairs',
        label: '계단으로 나가요',
        learnerExplanation: '엘리베이터가 보여도 계단으로 건물 밖에 나가요.',
        learnerPrompt: '밖으로 나가야 할 수 있어요.',
        options: [
          { correct: true, id: 'stairs', label: '계단' },
          { correct: false, id: 'elevator', label: '엘리베이터' },
        ],
        question: '밖으로 나갈 때 어디로 갈까요?',
        startMs: 74_920,
      },
      {
        actionSteps: ['가방으로 머리를 가려요', '건물에서 멀어져요', '담장에서 멀어져요'],
        endMs: 102_640,
        id: 'earthquake-full-outside-head',
        label: '밖에서 머리를 가려요',
        learnerExplanation: '가방으로 머리를 가리고 멀어져요.',
        learnerPrompt: '밖에도 유리와 간판이 떨어져요.',
        options: [
          { correct: true, id: 'head', label: '머리' },
          { correct: false, id: 'near-wall', label: '건물 바로 옆' },
        ],
        question: '밖에서는 무엇을 가릴까요?',
        startMs: 81_520,
      },
      {
        actionSteps: [
          '안전디딤돌 앱에서 지진 대피소를 찾아요',
          '넓은 공원으로 걸어가요',
          '넓은 운동장으로 걸어가요',
        ],
        endMs: 121_240,
        id: 'earthquake-full-open-space',
        label: '안전한 곳으로 걸어가요',
        learnerExplanation: '안전디딤돌 앱에서 지진 대피소를 보고 넓은 곳으로 가요.',
        learnerPrompt: '밖으로 나온 뒤 갈 곳을 찾아요.',
        options: [
          { correct: true, id: 'open-space', label: '공원이나 운동장' },
          { correct: false, id: 'car', label: '차' },
        ],
        question: '안전디딤돌을 못 보면 어디로 갈까요?',
        startMs: 102_640,
      },
      {
        actionSteps: ['튼튼한 건물을 찾아요', '안으로 들어가요', '몸을 지켜요'],
        endMs: 130_400,
        id: 'earthquake-full-sturdy-building',
        label: '튼튼한 건물로 가요',
        learnerExplanation: '넓은 곳이 없으면 튼튼한 건물로 가요.',
        learnerPrompt: '공원이나 운동장이 안 보일 수 있어요.',
        options: [
          { correct: true, id: 'strong-building', label: '튼튼한 건물' },
          { correct: false, id: 'near-building', label: '건물 바로 옆' },
        ],
        question: '넓은 곳이 없으면 어디로 갈까요?',
        startMs: 121_240,
      },
      {
        actionSteps: ['책상 아래로 가요', '책상 다리를 잡아요', '몸을 작게 해요'],
        endMs: 145_600,
        id: 'earthquake-full-office-desk',
        label: '책상 아래로 가요',
        learnerExplanation: '책상 아래에서 다리를 잡아요.',
        learnerPrompt: '사무실에서 지진이 났어요.',
        options: [
          { correct: true, id: 'desk', label: '책상 아래' },
          { correct: false, id: 'hall', label: '복도' },
        ],
        question: '사무실에서는 어디로 갈까요?',
        startMs: 130_400,
      },
      {
        actionSteps: ['선생님 말을 들어요', '창문에서 떨어져요', '운동장이나 넓은 공원으로 가요'],
        endMs: 175_400,
        id: 'earthquake-full-school-evacuation',
        label: '선생님 말을 들어요',
        learnerExplanation: '선생님 말을 듣고 창문에서 떨어져요.',
        learnerPrompt: '학교에서 지진이 났어요.',
        options: [
          { correct: true, id: 'teacher', label: '선생님' },
          { correct: false, id: 'alone', label: '혼자 뛰기' },
        ],
        question: '학교에서는 누구 말을 들을까요?',
        startMs: 145_600,
      },
      {
        actionSteps: ['다친 사람을 봐요', '다친 사람을 119에 알려요', '라디오나 공공기관 안내를 들어요'],
        endMs: 214_400,
        id: 'earthquake-full-after-report',
        label: '119와 방송을 기억해요',
        learnerExplanation: '다친 사람은 119에 알리고 방송을 들어요.',
        learnerPrompt: '다친 사람이 있을 수 있어요.',
        options: [
          { correct: true, id: 'call-119', label: '119' },
          { correct: false, id: 'rumor', label: '소문' },
        ],
        question: '다친 사람이 있으면 어디에 알릴까요?',
        startMs: 194_500,
      },
      {
        actionSteps: ['옷장 문 주변을 봐요', '보관함 문을 천천히 열어요', '쏟아진 물건이 있으면 어른에게 말해요'],
        endMs: 230_450,
        id: 'earthquake-full-return-door',
        label: '문은 천천히 열어요',
        learnerExplanation: '옷장이나 보관함 문을 천천히 열어요.',
        learnerPrompt: '옷장이나 보관함 문 뒤에 물건이 있을 수 있어요.',
        options: [
          { correct: true, id: 'slow-open', label: '천천히' },
          { correct: false, id: 'open-fast', label: '확 열기' },
        ],
        question: '옷장 문을 열 때 어떻게 할까요?',
        startMs: 214_400,
      },
      {
        actionSteps: ['가스 냄새나 새는 소리를 어른에게 말해요', '밖으로 나가요', '다시 쓰기 전 어른에게 물어봐요'],
        endMs: 251_880,
        id: 'earthquake-full-door-gas',
        label: '가스 냄새를 말해요',
        learnerExplanation: '가스 냄새를 어른에게 말하고 밖으로 나가요.',
        learnerPrompt: '가스 냄새나 새는 소리가 나요.',
        options: [
          { correct: true, id: 'tell-gas', label: '어른' },
          { correct: false, id: 'touch-gas', label: '혼자 만지기' },
        ],
        question: '가스 냄새가 나면 누구에게 말할까요?',
        startMs: 231_000,
      },
      {
        actionSteps: ['전선에서 떨어져요', '정전이면 손전등을 써요', '전선 문제를 어른에게 말해요'],
        endMs: 267_960,
        id: 'earthquake-full-electric-water',
        label: '전기는 어른에게 말해요',
        learnerExplanation: '정전이면 손전등을 쓰고 전선은 어른에게 말해요.',
        learnerPrompt: '전기가 고장 난 것 같아요.',
        options: [
          { correct: true, id: 'flashlight', label: '손전등' },
          { correct: false, id: 'elevator', label: '엘리베이터' },
        ],
        question: '정전이면 무엇을 쓸까요?',
        startMs: 251_880,
      },
      {
        actionSteps: ['수도관 고장을 어른에게 말해요', '수도꼭지 물은 기다려요', '화장실 물도 어른에게 물어봐요'],
        endMs: 285_640,
        id: 'earthquake-full-water-report',
        label: '물은 어른에게 먼저 말해요',
        learnerExplanation: '수도꼭지나 화장실 물은 어른에게 먼저 말해요.',
        learnerPrompt: '수도관이 고장 난 것 같아요.',
        options: [
          { correct: true, id: 'tell-adult', label: '어른' },
          { correct: false, id: 'touch-water', label: '혼자 만지기' },
        ],
        question: '물 쓰기 전에 누구에게 말할까요?',
        startMs: 267_960,
      },
      {
        actionSteps: [],
        endMs: 307_440,
        id: 'earthquake-full-outro-review',
        label: '마지막 복습',
        learnerExplanation: '또 흔들리면 다시 연습해요.',
        learnerPrompt: '마지막으로 다시 기억해요.',
        options: [],
        practiceMode: 'intro',
        question: '',
        startMs: 285_640,
      },
    ],
  },
]
